{
 "title": "Flask App Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, status) (rate(flask_http_request_total[1m]))",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Latency p95 (seconds)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(flask_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95 {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Status Breakdown",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total[1m]))",
     "legendFormat": "status {{status}}"
    }
   ]
  },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "{pod=~\"flask-app-deployment-.*\"}"
    }
   ]
  }
 ]
}